### ISSUE TITLE
Am having an issue with following your tutorial , on this part below 

### ISSUE THREAD

**Issue by huxaiphaer** [agiliq/building-api-django#33]
**Am a beginner in Django and I would like to know where exactly do I run this below -**

**Using the PollSerializer**
Let’s use the serializer to create a Poll object.

```
In [1]: from polls.serializers import PollSerializer

In [2]: from polls.models import Poll

In [3]: poll_serializer = PollSerializer(data={"question": "Mojito or Caipirinha?", "created_by": 1})

In [4]: poll_serializer.is_valid()
Out[4]: True

In [5]: poll = poll_serializer.save()

In [6]: poll.pk
Out[6]: 5
```
The poll.pk line tells us that the object has been commited to the DB. You can also use the serializer to update a Poll object.
```

In [9]: poll_serializer = PollSerializer(instance=poll, data={"question": "Mojito, Caipirinha or margarita?", "created_by": 1})

In [10]: poll_serializer.is_valid()
Out[10]: True

In [11]: poll_serializer.save()
Out[11]: <Poll: Mojito, Caipirinha or margarita?>

In [12]: Poll.objects.get(pk=5).question
Out[12]: 'Mojito, Caipirinha or margarita?'
```

Do we run it in the terminal? or we create a file and we run it inside there. I will be very happy for your help, and I really thank you for the tutorial, it's really nice.

**Comment by yashrastogi16** [comment]
@huxaiphaer 
You can run these commands in terminal. You need to be in the project directory. Follow the below commands.

$ python manage.py shell

you will get access to the terminal where you can execute the above code.

**Comment by huxaiphaer** [comment]
Thanks so much @yashrastogi16
